version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      # expose the Minecraft server port outside of container
      - 25565:25565
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      VERSION: "1.16.5"
      SEED: "-7871659279518394360"
      LEVEL_TYPE: "biomesoplenty"
      FORGEVERSION: "36.1.0"
    volumes:
      # use a named, managed volume for data volume
      - mc_forge:/data
      # attach local host directory "mods" in same directory as this compose file
      # all mods in this directory get copied into /data/mods at startup
      - ./mods:/mods:ro

volumes:
  mc_forge: {}
